# Generated by Django 3.1.8 on 2021-04-27 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yrb', '0002_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.CreateModel(
            name='YrbUser',
            fields=[
                ('cid', models.OneToOneField(db_column='cid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='yrb.yrbcustomer')),
                ('email', models.CharField(max_length=25)),
                ('password_hash', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'yrb_user',
                'unique_together': {('cid', 'email', 'password_hash')},
            },
        ),
    ]
