# Generated by Django 3.1.8 on 2021-05-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yrb', '0004_auto_20210428_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yrbuser',
            name='password_hash',
            field=models.CharField(max_length=100),
        ),
    ]
