# Generated by Django 3.1.8 on 2021-05-01 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yrb', '0005_auto_20210501_1326'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YrbUser',
        ),
    ]
