# Generated by Django 3.1.8 on 2021-05-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yrb', '0006_delete_yrbuser'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='yrbpurchase',
            index=models.Index(fields=['cid'], name='yrb_purchas_cid_254dd2_idx'),
        ),
    ]
