# Generated by Django 3.1.8 on 2021-05-02 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yrb', '0007_auto_20210501_1553'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='yrbpurchase',
            name='yrb_purchas_cid_254dd2_idx',
        ),
    ]
