# Generated by Django 3.1.8 on 2021-05-03 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yrb', '0010_auto_20210502_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yrbpurchase',
            name='club',
            field=models.ForeignKey(db_column='club', on_delete=django.db.models.deletion.DO_NOTHING, to='yrb.yrbclub'),
        ),
    ]
